// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF_ImovR4HDHnFav1-Lex7i4ewKFPOSr4',
    appId: '1:479970496626:web:3610aa338e9672018cf2eb',
    messagingSenderId: '479970496626',
    projectId: 'patientmonitor-4f0e8',
    authDomain: 'patientmonitor-4f0e8.firebaseapp.com',
    storageBucket: 'patientmonitor-4f0e8.firebasestorage.app',
    measurementId: 'G-4JTMV3L8LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEuTpnY3b4zKV80uREwxqT31v6JxxST4s',
    appId: '1:479970496626:android:47440f89c21170298cf2eb',
    messagingSenderId: '479970496626',
    projectId: 'patientmonitor-4f0e8',
    storageBucket: 'patientmonitor-4f0e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChXTlgdX4oBZovt7_78SZNIWVQmcaUCaA',
    appId: '1:479970496626:ios:98ca9ce9cea02ca58cf2eb',
    messagingSenderId: '479970496626',
    projectId: 'patientmonitor-4f0e8',
    storageBucket: 'patientmonitor-4f0e8.firebasestorage.app',
    iosBundleId: 'com.example.patientm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChXTlgdX4oBZovt7_78SZNIWVQmcaUCaA',
    appId: '1:479970496626:ios:98ca9ce9cea02ca58cf2eb',
    messagingSenderId: '479970496626',
    projectId: 'patientmonitor-4f0e8',
    storageBucket: 'patientmonitor-4f0e8.firebasestorage.app',
    iosBundleId: 'com.example.patientm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF_ImovR4HDHnFav1-Lex7i4ewKFPOSr4',
    appId: '1:479970496626:web:96da2536bf598b728cf2eb',
    messagingSenderId: '479970496626',
    projectId: 'patientmonitor-4f0e8',
    authDomain: 'patientmonitor-4f0e8.firebaseapp.com',
    storageBucket: 'patientmonitor-4f0e8.firebasestorage.app',
    measurementId: 'G-0NXM3NSWMY',
  );
}
